name: Check notebooks

on:
  push:
    branches: [main]
    paths:
      - 'exercises/**'
      - 'notebook-checks/**'
      - '.github/workflows/CheckNotebooks.yml'
  pull_request:
    branches: [main]
    paths:
      - 'exercises/**'
      - 'notebook-checks/**'
      - '.github/workflows/CheckNotebooks.yml'

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      actions: write
      contents: read
      pull-requests: read
      statuses: write
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: julia-actions/setup-julia@5c9647d97b78a5debe5164e9eec09d653d29bd71 # v2.6.1
        with:
          version: '1.12'
      - uses: julia-actions/cache@v2
      - name: Instantiate packages
        run: julia -e 'using Pkg; Pkg.activate("./exercises/solved_notebooks"); Pkg.instantiate()'
      - name: Build and deploy
        run: julia --color=yes notebook-checks/check_notebooks.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
